apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-server-ingress
  namespace: http-test
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: http-server.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: http-server
            port:
              number: 80
